# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa47a93d16e68158261d189490bbcb1e2128c20749b3c6df1244842778dcaa76c650cfc96e6fb160c865a44dcc1bfa0a85ed80837ea87dd7e643d22ea1cf4a20

test:
  secret_key_base: 282604bb76f2c7ec48b82932d0618efe020827f32e6c9daeeb910f71e44418927dfd572b592eb06a1ab8eb606f84a21def5a0bc2ea88f7c9d9f26ca57ffb602a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
